//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerWebServices.CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://google.com/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://google.com/", ConfigurationName="CustomerService.Customer1Soap")]
    public interface Customer1Soap {
        
        // CODEGEN: Generating message contract since element name GetCustomerDetailsResult from namespace http://google.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://google.com/GetCustomerDetails", ReplyAction="*")]
        CustomerWebServices.CustomerService.GetCustomerDetailsResponse GetCustomerDetails(CustomerWebServices.CustomerService.GetCustomerDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://google.com/GetCustomerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerWebServices.CustomerService.GetCustomerDetailsResponse> GetCustomerDetailsAsync(CustomerWebServices.CustomerService.GetCustomerDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomerByIDResult from namespace http://google.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://google.com/GetCustomerByID", ReplyAction="*")]
        CustomerWebServices.CustomerService.GetCustomerByIDResponse GetCustomerByID(CustomerWebServices.CustomerService.GetCustomerByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://google.com/GetCustomerByID", ReplyAction="*")]
        System.Threading.Tasks.Task<CustomerWebServices.CustomerService.GetCustomerByIDResponse> GetCustomerByIDAsync(CustomerWebServices.CustomerService.GetCustomerByIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerDetails", Namespace="http://google.com/", Order=0)]
        public CustomerWebServices.CustomerService.GetCustomerDetailsRequestBody Body;
        
        public GetCustomerDetailsRequest() {
        }
        
        public GetCustomerDetailsRequest(CustomerWebServices.CustomerService.GetCustomerDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomerDetailsRequestBody {
        
        public GetCustomerDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerDetailsResponse", Namespace="http://google.com/", Order=0)]
        public CustomerWebServices.CustomerService.GetCustomerDetailsResponseBody Body;
        
        public GetCustomerDetailsResponse() {
        }
        
        public GetCustomerDetailsResponse(CustomerWebServices.CustomerService.GetCustomerDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://google.com/")]
    public partial class GetCustomerDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CustomerWebServices.CustomerService.Customer[] GetCustomerDetailsResult;
        
        public GetCustomerDetailsResponseBody() {
        }
        
        public GetCustomerDetailsResponseBody(CustomerWebServices.CustomerService.Customer[] GetCustomerDetailsResult) {
            this.GetCustomerDetailsResult = GetCustomerDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByID", Namespace="http://google.com/", Order=0)]
        public CustomerWebServices.CustomerService.GetCustomerByIDRequestBody Body;
        
        public GetCustomerByIDRequest() {
        }
        
        public GetCustomerByIDRequest(CustomerWebServices.CustomerService.GetCustomerByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://google.com/")]
    public partial class GetCustomerByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public GetCustomerByIDRequestBody() {
        }
        
        public GetCustomerByIDRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerByIDResponse", Namespace="http://google.com/", Order=0)]
        public CustomerWebServices.CustomerService.GetCustomerByIDResponseBody Body;
        
        public GetCustomerByIDResponse() {
        }
        
        public GetCustomerByIDResponse(CustomerWebServices.CustomerService.GetCustomerByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://google.com/")]
    public partial class GetCustomerByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CustomerWebServices.CustomerService.Customer GetCustomerByIDResult;
        
        public GetCustomerByIDResponseBody() {
        }
        
        public GetCustomerByIDResponseBody(CustomerWebServices.CustomerService.Customer GetCustomerByIDResult) {
            this.GetCustomerByIDResult = GetCustomerByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Customer1SoapChannel : CustomerWebServices.CustomerService.Customer1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Customer1SoapClient : System.ServiceModel.ClientBase<CustomerWebServices.CustomerService.Customer1Soap>, CustomerWebServices.CustomerService.Customer1Soap {
        
        public Customer1SoapClient() {
        }
        
        public Customer1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Customer1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Customer1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Customer1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerWebServices.CustomerService.GetCustomerDetailsResponse CustomerWebServices.CustomerService.Customer1Soap.GetCustomerDetails(CustomerWebServices.CustomerService.GetCustomerDetailsRequest request) {
            return base.Channel.GetCustomerDetails(request);
        }
        
        public CustomerWebServices.CustomerService.Customer[] GetCustomerDetails() {
            CustomerWebServices.CustomerService.GetCustomerDetailsRequest inValue = new CustomerWebServices.CustomerService.GetCustomerDetailsRequest();
            inValue.Body = new CustomerWebServices.CustomerService.GetCustomerDetailsRequestBody();
            CustomerWebServices.CustomerService.GetCustomerDetailsResponse retVal = ((CustomerWebServices.CustomerService.Customer1Soap)(this)).GetCustomerDetails(inValue);
            return retVal.Body.GetCustomerDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CustomerWebServices.CustomerService.GetCustomerDetailsResponse> CustomerWebServices.CustomerService.Customer1Soap.GetCustomerDetailsAsync(CustomerWebServices.CustomerService.GetCustomerDetailsRequest request) {
            return base.Channel.GetCustomerDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerWebServices.CustomerService.GetCustomerDetailsResponse> GetCustomerDetailsAsync() {
            CustomerWebServices.CustomerService.GetCustomerDetailsRequest inValue = new CustomerWebServices.CustomerService.GetCustomerDetailsRequest();
            inValue.Body = new CustomerWebServices.CustomerService.GetCustomerDetailsRequestBody();
            return ((CustomerWebServices.CustomerService.Customer1Soap)(this)).GetCustomerDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CustomerWebServices.CustomerService.GetCustomerByIDResponse CustomerWebServices.CustomerService.Customer1Soap.GetCustomerByID(CustomerWebServices.CustomerService.GetCustomerByIDRequest request) {
            return base.Channel.GetCustomerByID(request);
        }
        
        public CustomerWebServices.CustomerService.Customer GetCustomerByID(int ID) {
            CustomerWebServices.CustomerService.GetCustomerByIDRequest inValue = new CustomerWebServices.CustomerService.GetCustomerByIDRequest();
            inValue.Body = new CustomerWebServices.CustomerService.GetCustomerByIDRequestBody();
            inValue.Body.ID = ID;
            CustomerWebServices.CustomerService.GetCustomerByIDResponse retVal = ((CustomerWebServices.CustomerService.Customer1Soap)(this)).GetCustomerByID(inValue);
            return retVal.Body.GetCustomerByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CustomerWebServices.CustomerService.GetCustomerByIDResponse> CustomerWebServices.CustomerService.Customer1Soap.GetCustomerByIDAsync(CustomerWebServices.CustomerService.GetCustomerByIDRequest request) {
            return base.Channel.GetCustomerByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CustomerWebServices.CustomerService.GetCustomerByIDResponse> GetCustomerByIDAsync(int ID) {
            CustomerWebServices.CustomerService.GetCustomerByIDRequest inValue = new CustomerWebServices.CustomerService.GetCustomerByIDRequest();
            inValue.Body = new CustomerWebServices.CustomerService.GetCustomerByIDRequestBody();
            inValue.Body.ID = ID;
            return ((CustomerWebServices.CustomerService.Customer1Soap)(this)).GetCustomerByIDAsync(inValue);
        }
    }
}
